// Generated by https://quicktype.io

import { Neo } from "./Neo";
import { NeoLinks } from "./NeoLinks";

/**
 * keys are date strings (YYYY-MM-DD)
 */
export type NeoDateMap = { [key: string]: Neo[] };

export interface NeoFeed {
  links: NeoLinks;
  element_count: number;
  near_earth_objects: NeoDateMap;
}
